// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fakebook.domain;

import com.fakebook.domain.Comment;
import com.fakebook.domain.CommentDataOnDemand;
import com.fakebook.domain.Fakebooker;
import com.fakebook.domain.FakebookerDataOnDemand;
import com.fakebook.domain.Post;
import com.fakebook.domain.PostDataOnDemand;
import com.fakebook.service.CommentService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CommentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CommentDataOnDemand: @Component;
    
    private Random CommentDataOnDemand.rnd = new SecureRandom();
    
    private List<Comment> CommentDataOnDemand.data;
    
    @Autowired
    private FakebookerDataOnDemand CommentDataOnDemand.fakebookerDataOnDemand;
    
    @Autowired
    private PostDataOnDemand CommentDataOnDemand.postDataOnDemand;
    
    @Autowired
    CommentService CommentDataOnDemand.commentService;
    
    public Comment CommentDataOnDemand.getNewTransientComment(int index) {
        Comment obj = new Comment();
        setMessage(obj, index);
        setOwner(obj, index);
        setPost(obj, index);
        return obj;
    }
    
    public void CommentDataOnDemand.setMessage(Comment obj, int index) {
        String message = "message_" + index;
        obj.setMessage(message);
    }
    
    public void CommentDataOnDemand.setOwner(Comment obj, int index) {
        Fakebooker owner = fakebookerDataOnDemand.getRandomFakebooker();
        obj.setOwner(owner);
    }
    
    public void CommentDataOnDemand.setPost(Comment obj, int index) {
        Post post = postDataOnDemand.getRandomPost();
        obj.setPost(post);
    }
    
    public Comment CommentDataOnDemand.getSpecificComment(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Comment obj = data.get(index);
        Long id = obj.getId();
        return commentService.findComment(id);
    }
    
    public Comment CommentDataOnDemand.getRandomComment() {
        init();
        Comment obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return commentService.findComment(id);
    }
    
    public boolean CommentDataOnDemand.modifyComment(Comment obj) {
        return false;
    }
    
    public void CommentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = commentService.findCommentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Comment' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Comment>();
        for (int i = 0; i < 10; i++) {
            Comment obj = getNewTransientComment(i);
            try {
                commentService.saveComment(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
