// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fakebook.domain;

import com.fakebook.domain.FakebookerIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FakebookerIntegrationTest_Roo_Configurable {
    
    declare @type: FakebookerIntegrationTest: @Configurable;
    
}
