// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fakebook.domain;

import com.fakebook.domain.FakebookerDataOnDemand;
import com.fakebook.domain.FakebookerIntegrationTest;
import com.fakebook.service.FakebookerService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FakebookerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FakebookerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FakebookerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FakebookerIntegrationTest: @Transactional;
    
    @Autowired
    private FakebookerDataOnDemand FakebookerIntegrationTest.dod;
    
    @Autowired
    FakebookerService FakebookerIntegrationTest.fakebookerService;
    
    @Test
    public void FakebookerIntegrationTest.testCountAllFakebookers() {
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to initialize correctly", dod.getRandomFakebooker());
        long count = fakebookerService.countAllFakebookers();
        Assert.assertTrue("Counter for 'Fakebooker' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FakebookerIntegrationTest.testFindFakebooker() {
        Fakebooker obj = dod.getRandomFakebooker();
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to provide an identifier", id);
        obj = fakebookerService.findFakebooker(id);
        Assert.assertNotNull("Find method for 'Fakebooker' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Fakebooker' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FakebookerIntegrationTest.testFindAllFakebookers() {
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to initialize correctly", dod.getRandomFakebooker());
        long count = fakebookerService.countAllFakebookers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Fakebooker', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Fakebooker> result = fakebookerService.findAllFakebookers();
        Assert.assertNotNull("Find all method for 'Fakebooker' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Fakebooker' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FakebookerIntegrationTest.testFindFakebookerEntries() {
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to initialize correctly", dod.getRandomFakebooker());
        long count = fakebookerService.countAllFakebookers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Fakebooker> result = fakebookerService.findFakebookerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Fakebooker' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Fakebooker' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FakebookerIntegrationTest.testFlush() {
        Fakebooker obj = dod.getRandomFakebooker();
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to provide an identifier", id);
        obj = fakebookerService.findFakebooker(id);
        Assert.assertNotNull("Find method for 'Fakebooker' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFakebooker(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Fakebooker' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FakebookerIntegrationTest.testUpdateFakebookerUpdate() {
        Fakebooker obj = dod.getRandomFakebooker();
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to provide an identifier", id);
        obj = fakebookerService.findFakebooker(id);
        boolean modified =  dod.modifyFakebooker(obj);
        Integer currentVersion = obj.getVersion();
        Fakebooker merged = fakebookerService.updateFakebooker(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Fakebooker' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FakebookerIntegrationTest.testSaveFakebooker() {
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to initialize correctly", dod.getRandomFakebooker());
        Fakebooker obj = dod.getNewTransientFakebooker(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Fakebooker' identifier to be null", obj.getId());
        fakebookerService.saveFakebooker(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'Fakebooker' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FakebookerIntegrationTest.testDeleteFakebooker() {
        Fakebooker obj = dod.getRandomFakebooker();
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Fakebooker' failed to provide an identifier", id);
        obj = fakebookerService.findFakebooker(id);
        fakebookerService.deleteFakebooker(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Fakebooker' with identifier '" + id + "'", fakebookerService.findFakebooker(id));
    }
    
}
