// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fakebook.domain;

import com.fakebook.domain.Fakebooker;
import com.fakebook.domain.FakebookerDataOnDemand;
import com.fakebook.service.FakebookerService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FakebookerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FakebookerDataOnDemand: @Component;
    
    private Random FakebookerDataOnDemand.rnd = new SecureRandom();
    
    private List<Fakebooker> FakebookerDataOnDemand.data;
    
    @Autowired
    FakebookerService FakebookerDataOnDemand.fakebookerService;
    
    public Fakebooker FakebookerDataOnDemand.getNewTransientFakebooker(int index) {
        Fakebooker obj = new Fakebooker();
        setBirthDate(obj, index);
        setEmail(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        setMiddleName(obj, index);
        setPassword(obj, index);
        return obj;
    }
    
    public void FakebookerDataOnDemand.setBirthDate(Fakebooker obj, int index) {
        Date birthDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setBirthDate(birthDate);
    }
    
    public void FakebookerDataOnDemand.setEmail(Fakebooker obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void FakebookerDataOnDemand.setFirstName(Fakebooker obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void FakebookerDataOnDemand.setLastName(Fakebooker obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void FakebookerDataOnDemand.setMiddleName(Fakebooker obj, int index) {
        String middleName = "middleName_" + index;
        obj.setMiddleName(middleName);
    }
    
    public void FakebookerDataOnDemand.setPassword(Fakebooker obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public Fakebooker FakebookerDataOnDemand.getSpecificFakebooker(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Fakebooker obj = data.get(index);
        Long id = obj.getId();
        return fakebookerService.findFakebooker(id);
    }
    
    public Fakebooker FakebookerDataOnDemand.getRandomFakebooker() {
        init();
        Fakebooker obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return fakebookerService.findFakebooker(id);
    }
    
    public boolean FakebookerDataOnDemand.modifyFakebooker(Fakebooker obj) {
        return false;
    }
    
    public void FakebookerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = fakebookerService.findFakebookerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Fakebooker' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Fakebooker>();
        for (int i = 0; i < 10; i++) {
            Fakebooker obj = getNewTransientFakebooker(i);
            try {
                fakebookerService.saveFakebooker(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
