// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.fakebook.domain;

import com.fakebook.domain.Fakebooker;
import com.fakebook.domain.FakebookerDataOnDemand;
import com.fakebook.domain.Post;
import com.fakebook.domain.PostDataOnDemand;
import com.fakebook.service.PostService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PostDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PostDataOnDemand: @Component;
    
    private Random PostDataOnDemand.rnd = new SecureRandom();
    
    private List<Post> PostDataOnDemand.data;
    
    @Autowired
    private FakebookerDataOnDemand PostDataOnDemand.fakebookerDataOnDemand;
    
    @Autowired
    PostService PostDataOnDemand.postService;
    
    public Post PostDataOnDemand.getNewTransientPost(int index) {
        Post obj = new Post();
        setMessage(obj, index);
        setOwner(obj, index);
        return obj;
    }
    
    public void PostDataOnDemand.setMessage(Post obj, int index) {
        String message = "message_" + index;
        obj.setMessage(message);
    }
    
    public void PostDataOnDemand.setOwner(Post obj, int index) {
        Fakebooker owner = fakebookerDataOnDemand.getRandomFakebooker();
        obj.setOwner(owner);
    }
    
    public Post PostDataOnDemand.getSpecificPost(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Post obj = data.get(index);
        Long id = obj.getId();
        return postService.findPost(id);
    }
    
    public Post PostDataOnDemand.getRandomPost() {
        init();
        Post obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return postService.findPost(id);
    }
    
    public boolean PostDataOnDemand.modifyPost(Post obj) {
        return false;
    }
    
    public void PostDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = postService.findPostEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Post' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Post>();
        for (int i = 0; i < 10; i++) {
            Post obj = getNewTransientPost(i);
            try {
                postService.savePost(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
